server:
   port: 8088

---
spring:
  profiles:
    active: dev


---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    name: sa
    password:

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: ${spring.datasource.url}
    user: sa
    password:
    default-schema: PUBLIC
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: h2
  h2:
    console:
      enabled: true
      path: /h2-conole


---

---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    name: sa
    password:

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: ${spring.datasource.url}
    user: sa
    password:
    default-schema: PUBLIC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: h2
  h2:
    console:
      enabled: true
      path: /h2-conole


---